import { cp, mkdir, readFile, writeFile, access } from 'node:fs/promises'
import path from 'node:path'

import { boolFlag, optionalFlag, requireFlag, type ParsedArgs } from '../args'

/**
 * `tenant-cli create --slug <slug> --domain <domain> [--template <path>]`
 *
 * Scaffolds a new tenant Astro app under apps/sites/<slug>/ by copying a
 * template (defaults to apps/sites/keukenfaqs). Updates package.json name,
 * wrangler project name, and writes a placeholder tenant.config.json so the
 * site can be developed against fixtures before Payload is populated.
 *
 * Use the `migrate` command after create to import WordPress content into
 * the tenant's Payload record.
 */
export async function runCreate(args: ParsedArgs): Promise<void> {
  const slug = requireFlag(args, 'slug')
  const domain = requireFlag(args, 'domain')
  const name = optionalFlag(args, 'name') ?? slug
  const cwd = process.cwd()
  const template = path.resolve(optionalFlag(args, 'template') ?? path.join(cwd, 'apps/sites/keukenfaqs'))
  const destination = path.resolve(path.join(cwd, 'apps/sites', slug))

  if (await exists(destination)) {
    throw new Error(`Destination already exists: ${destination}`)
  }
  if (!(await exists(template))) {
    throw new Error(`Template not found: ${template}`)
  }

  console.log(`[tenant-cli create] copying ${template} -> ${destination}`)
  await mkdir(path.dirname(destination), { recursive: true })
  await cp(template, destination, {
    recursive: true,
    filter: (src) => {
      // Skip volatile / per-tenant artefacts. They are regenerated by sync.
      const rel = path.relative(template, src)
      if (rel.startsWith('node_modules')) return false
      if (rel.startsWith('dist') || rel.startsWith('.astro') || rel.startsWith('.wrangler')) return false
      if (rel.startsWith('src/content/blog') || rel.startsWith('src/content/pages')) return false
      if (rel.startsWith('src/data/money-pages')) return false
      if (rel === 'tenant.config.json') return false
      return true
    },
  })

  // Rewrite package.json `name`.
  const pkgPath = path.join(destination, 'package.json')
  const pkg = JSON.parse(await readFile(pkgPath, 'utf8'))
  pkg.name = `@astropayload/site-${slug}`
  await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8')

  // Rewrite wrangler project name.
  const wranglerPath = path.join(destination, 'wrangler.jsonc')
  if (await exists(wranglerPath)) {
    const w = await readFile(wranglerPath, 'utf8')
    const updated = w.replace(/"name":\s*"[^"]+"/, `"name": "${slug}"`)
    await writeFile(wranglerPath, updated, 'utf8')
  }

  // Bootstrap tenant.config.json so `astro dev` works before the first sync.
  const stubConfig = {
    id: 'placeholder',
    slug,
    name,
    domain,
    url: `https://${domain}`,
    locale: 'nl-NL',
    themeTokens: {},
    siteTitle: name,
    siteDescription: '',
    socialLinks: [],
    navMenus: [],
    syncedAt: new Date().toISOString(),
  }
  await writeFile(
    path.join(destination, 'tenant.config.json'),
    JSON.stringify(stubConfig, null, 2) + '\n',
    'utf8'
  )

  console.log(`[tenant-cli create] scaffolded apps/sites/${slug}`)

  // Best-effort: also create the tenant row in Payload (skipped if PAYLOAD_URL
  // is not configured, or if --skip-payload-create was passed — used by the
  // tenant-scaffold CI workflow where the row already exists in Payload).
  const payloadUrl = process.env.PAYLOAD_URL
  const apiKey = process.env.PAYLOAD_API_KEY
  const skipPayloadCreate = boolFlag(args, 'skip-payload-create')
  if (skipPayloadCreate) {
    console.log('[tenant-cli create] --skip-payload-create set; not touching Payload.')
  } else if (payloadUrl && apiKey) {
    try {
      const res = await fetch(`${payloadUrl.replace(/\/+$/, '')}/api/tenants`, {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          Authorization: `users API-Key ${apiKey}`,
        },
        body: JSON.stringify({
          slug,
          name,
          domain,
          locale: optionalFlag(args, 'locale') ?? 'nl-NL',
          siteTitle: name,
          siteDescription: optionalFlag(args, 'description') ?? `Welcome to ${name}.`,
        }),
      })
      if (res.ok) console.log(`[tenant-cli create] also created Payload tenant '${slug}'`)
      else console.warn(`[tenant-cli create] Payload tenant create failed: ${res.status} (skipped)`)
    } catch (err) {
      console.warn(`[tenant-cli create] could not reach Payload at ${payloadUrl} (skipped):`, err)
    }
  } else {
    console.log('Next steps:')
    console.log(`  1. Add a tenants row in Payload with slug='${slug}', domain='${domain}'`)
    console.log(`  2. TENANT=${slug} pnpm --filter @astropayload/site-${slug} sync:content`)
    console.log(`  3. TENANT=${slug} pnpm --filter @astropayload/site-${slug} dev`)
  }
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}
