#!/usr/bin/env bash
# Tenant scaffold — mirrors .github/workflows/tenant-scaffold.yml
set -euo pipefail

TENANT_SLUG="${tenant_slug:-${TENANT_SLUG:-}}"
TENANT_DOMAIN="${tenant_domain:-${TENANT_DOMAIN:-}}"
TENANT_NAME="${tenant_name:-${TENANT_NAME:-}}"
TEMPLATE="${template:-apps/sites/keukenfaqs}"
RUN_URL="${BUILD_URL:-}"
PAYLOAD_URL="${PAYLOAD_URL:-}"
DEPLOY_REPORT_TOKEN="${DEPLOY_REPORT_TOKEN:-}"
GH_TOKEN="${GH_TOKEN:-${PLATFORM_GIT_TOKEN:-}}"

export TENANT_SLUG TENANT_DOMAIN TENANT_NAME TEMPLATE GH_TOKEN

if [ -z "$TENANT_SLUG" ] || [ -z "$TENANT_DOMAIN" ] || [ -z "$TENANT_NAME" ]; then
  echo "tenant_slug, tenant_domain, and tenant_name are required" >&2
  exit 1
fi

if ! echo "$TENANT_SLUG" | grep -Eq '^[a-z][a-z0-9-]*$'; then
  echo "Invalid slug '$TENANT_SLUG'" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE="${WORKSPACE:-$(pwd)}"
cd "$WORKSPACE"

# Pipeline from SCM: workspace is the platform repo. Re-fetch full history for push.
if [ -d .git ]; then
  git fetch --unshallow 2>/dev/null || git fetch --depth=1000 2>/dev/null || true
else
  bash "$SCRIPT_DIR/checkout-platform.sh"
  cd platform
fi

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

if [ -d "apps/sites/${TENANT_SLUG}" ]; then
  echo "apps/sites/${TENANT_SLUG} already exists" >&2
  exit 1
fi

bash "$SCRIPT_DIR/setup-node-pnpm.sh"
source "$SCRIPT_DIR/load-node-pnpm.sh"
pnpm install --frozen-lockfile

if [ -n "$PAYLOAD_URL" ] && [ -n "$DEPLOY_REPORT_TOKEN" ] && [ -n "$RUN_URL" ]; then
  pnpm --filter @astropayload/payload report:deploy -- \
    --kind scaffold \
    --slug "$TENANT_SLUG" \
    --status in_progress \
    --run-url "$RUN_URL" || true
fi

pnpm tenant-cli create \
  --slug "$TENANT_SLUG" \
  --domain "$TENANT_DOMAIN" \
  --name "$TENANT_NAME" \
  --template "$TEMPLATE" \
  --skip-payload-create

if [ -f "apps/sites/${TENANT_SLUG}/tenant.config.json" ]; then
  git add -f "apps/sites/${TENANT_SLUG}/tenant.config.json"
fi

git config user.name "astropayload-bot"
git config user.email "bot@astropayload.local"

BRANCH="scaffold/${TENANT_SLUG}"
git checkout -b "$BRANCH"
git add "apps/sites/${TENANT_SLUG}"

cat > /tmp/commit-msg.txt <<EOF
feat(tenants): scaffold ${TENANT_SLUG} (${TENANT_DOMAIN})

Generated by Jenkins tenant-scaffold job.
EOF
git commit -F /tmp/commit-msg.txt

if [ -z "$GH_TOKEN" ]; then
  echo "GH_TOKEN or PLATFORM_GIT_TOKEN required to push scaffold branch" >&2
  exit 1
fi

git push "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git" \
  "$BRANCH" --force

PR_URL=""
if command -v gh >/dev/null 2>&1; then
  export GH_TOKEN
  existing="$(gh pr list --head "$BRANCH" --json url --jq '.[0].url' 2>/dev/null || true)"
  if [ -n "$existing" ]; then
    PR_URL="$existing"
  else
    PR_URL="$(gh pr create \
      --title "Scaffold tenant: ${TENANT_SLUG}" \
      --body "Auto-generated scaffold for **${TENANT_NAME}** (\`${TENANT_SLUG}\`, ${TENANT_DOMAIN})." \
      --head "$BRANCH" \
      --base "${PLATFORM_GIT_BRANCH:-main}" 2>/dev/null || true)"
  fi
fi

if [ -n "$PAYLOAD_URL" ] && [ -n "$DEPLOY_REPORT_TOKEN" ]; then
  pnpm --filter @astropayload/payload report:deploy -- \
    --kind scaffold \
    --slug "$TENANT_SLUG" \
    --status success \
    --run-url "$RUN_URL" \
    --pr-url "$PR_URL" || true
fi

echo "Scaffold complete for $TENANT_SLUG${PR_URL:+ — PR: $PR_URL}"
