/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    'blog-posts': BlogPost;
    pages: Page;
    top10s: Top10;
    products: Product;
    businesses: Business;
    media: Media;
    redirects: Redirect;
    'nav-menus': NavMenu;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    top10s: Top10SSelect<false> | Top10SSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'nav-menus': NavMenusSelect<false> | NavMenusSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used as the tenant identifier in URLs, builds, and Wrangler project names. Lowercase letters, digits, and hyphens only — auto-normalized on save.
   */
  slug: string;
  /**
   * Primary domain, e.g. keukenfaqs.nl (no protocol).
   */
  domain: string;
  locale: 'nl-NL' | 'en-GB' | 'en-US' | 'de-DE' | 'fr-FR' | 'es-ES';
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * Default Open Graph image (1200×630).
   */
  ogImage?: (number | null) | Media;
  /**
   * Emitted as CSS variables in the tenant site.
   */
  themeTokens?: {
    primary?: string | null;
    primaryDark?: string | null;
    accent?: string | null;
    background?: string | null;
    text?: string | null;
    muted?: string | null;
    fontHeading?: string | null;
    fontBody?: string | null;
    radius?: string | null;
  };
  siteTitle: string;
  siteDescription: string;
  titleSuffix?: string | null;
  robots?: ('index,follow' | 'noindex,follow' | 'noindex,nofollow') | null;
  /**
   * e.g. G-43H5NMZVHK
   */
  ga4Id?: string | null;
  gtmId?: string | null;
  plausibleDomain?: string | null;
  /**
   * Bol.com Partner Programma publisher ID (s=...).
   */
  bolPublisherId?: string | null;
  awinId?: string | null;
  amazonTag?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'youtube' | 'tiktok' | 'pinterest' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wrangler project name (defaults to slug).
   */
  cloudflareProject?: string | null;
  /**
   * GitHub Actions workflow file used to rebuild this tenant.
   */
  githubWorkflow?: string | null;
  /**
   * When unchecked, content changes do NOT trigger a rebuild.
   */
  webhookEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('super-admin' | 'tenant-admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * URL slug. Lowercase, hyphens only.
   */
  slug: string;
  description: string;
  pubDate: string;
  updatedDate?: string | null;
  heroImage?: (number | null) | Media;
  author?: string | null;
  categories?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Per-page SEO overrides. Falls back to the tenant defaults when blank.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * e.g. noindex,follow
     */
    robots?: string | null;
    /**
     * Override canonical URL if different from this site.
     */
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * URL slug. Lowercase, hyphens only.
   */
  slug: string;
  description?: string | null;
  pubDate?: string | null;
  updatedDate?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Per-page SEO overrides. Falls back to the tenant defaults when blank.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * e.g. noindex,follow
     */
    robots?: string | null;
    /**
     * Override canonical URL if different from this site.
     */
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top10s".
 */
export interface Top10 {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * URL slug. Lowercase, hyphens only.
   */
  slug: string;
  h1?: string | null;
  categorySingular?: string | null;
  categoryPlural?: string | null;
  intro?: string | null;
  conclusion?: string | null;
  metaDescription?: string | null;
  ogDescription?: string | null;
  /**
   * Human-readable, e.g. "2 jan. 2026".
   */
  publishedAt?: string | null;
  lastUpdated?: string | null;
  products?:
    | {
        rank: number;
        name: string;
        imageUrl?: string | null;
        description?: string | null;
        affiliateUrl?: string | null;
        affiliateNetwork?: ('bol' | 'awin' | 'amazon' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answerHtml: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Per-page SEO overrides. Falls back to the tenant defaults when blank.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * e.g. noindex,follow
     */
    robots?: string | null;
    /**
     * Override canonical URL if different from this site.
     */
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  title?: string | null;
  /**
   * URL slug. Lowercase, hyphens only.
   */
  slug: string;
  category?: string | null;
  intro?: string | null;
  description?: string | null;
  rating?: number | null;
  ratingOutOf?: number | null;
  imageUrl?: string | null;
  image?: (number | null) | Media;
  affiliateUrl?: string | null;
  affiliateNetwork?: ('bol' | 'awin' | 'amazon' | 'other') | null;
  affiliateCta?: string | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  pros?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  metaDescription?: string | null;
  ogDescription?: string | null;
  publishedAt?: string | null;
  lastUpdated?: string | null;
  /**
   * Per-page SEO overrides. Falls back to the tenant defaults when blank.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * e.g. noindex,follow
     */
    robots?: string | null;
    /**
     * Override canonical URL if different from this site.
     */
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  title?: string | null;
  /**
   * URL slug. Lowercase, hyphens only.
   */
  slug: string;
  city?: string | null;
  address?: string | null;
  websiteUrl?: string | null;
  googleMapsUrl?: string | null;
  intro?: string | null;
  metaDescription?: string | null;
  ogDescription?: string | null;
  publishedAt?: string | null;
  lastUpdated?: string | null;
  /**
   * Per-page SEO overrides. Falls back to the tenant defaults when blank.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * e.g. noindex,follow
     */
    robots?: string | null;
    /**
     * Override canonical URL if different from this site.
     */
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Source path, e.g. /old-page/
   */
  from: string;
  /**
   * Destination path or full URL.
   */
  to: string;
  status: '301' | '302' | '307' | '308';
  /**
   * Optional. Why this redirect exists.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-menus".
 */
export interface NavMenu {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  location: 'header' | 'footer' | 'mobile';
  items?:
    | {
        label: string;
        href: string;
        rel?: string | null;
        children?:
          | {
              label: string;
              href: string;
              rel?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'top10s';
        value: number | Top10;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'nav-menus';
        value: number | NavMenu;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  locale?: T;
  logo?: T;
  favicon?: T;
  ogImage?: T;
  themeTokens?:
    | T
    | {
        primary?: T;
        primaryDark?: T;
        accent?: T;
        background?: T;
        text?: T;
        muted?: T;
        fontHeading?: T;
        fontBody?: T;
        radius?: T;
      };
  siteTitle?: T;
  siteDescription?: T;
  titleSuffix?: T;
  robots?: T;
  ga4Id?: T;
  gtmId?: T;
  plausibleDomain?: T;
  bolPublisherId?: T;
  awinId?: T;
  amazonTag?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  cloudflareProject?: T;
  githubWorkflow?: T;
  webhookEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  pubDate?: T;
  updatedDate?: T;
  heroImage?: T;
  author?: T;
  categories?:
    | T
    | {
        value?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        robots?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  pubDate?: T;
  updatedDate?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        robots?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top10s_select".
 */
export interface Top10SSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  h1?: T;
  categorySingular?: T;
  categoryPlural?: T;
  intro?: T;
  conclusion?: T;
  metaDescription?: T;
  ogDescription?: T;
  publishedAt?: T;
  lastUpdated?: T;
  products?:
    | T
    | {
        rank?: T;
        name?: T;
        imageUrl?: T;
        description?: T;
        affiliateUrl?: T;
        affiliateNetwork?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answerHtml?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        robots?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  title?: T;
  slug?: T;
  category?: T;
  intro?: T;
  description?: T;
  rating?: T;
  ratingOutOf?: T;
  imageUrl?: T;
  image?: T;
  affiliateUrl?: T;
  affiliateNetwork?: T;
  affiliateCta?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  pros?:
    | T
    | {
        value?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        value?: T;
        id?: T;
      };
  metaDescription?: T;
  ogDescription?: T;
  publishedAt?: T;
  lastUpdated?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        robots?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  title?: T;
  slug?: T;
  city?: T;
  address?: T;
  websiteUrl?: T;
  googleMapsUrl?: T;
  intro?: T;
  metaDescription?: T;
  ogDescription?: T;
  publishedAt?: T;
  lastUpdated?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        robots?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  tenant?: T;
  from?: T;
  to?: T;
  status?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav-menus_select".
 */
export interface NavMenusSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        href?: T;
        rel?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              rel?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}